#!/bin/bash

read -p "Enter a number: " num

if ((num == 10)); then
	echo "you have entered $num"
fi

if ((num > 10)); then
	echo "your number is greater than 10"
else
	echo "your number is less than 10"
fi

touch file1 && vim file1

[ -d temp ] || mkdir temp
